// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioTrackerTool.Infrastructure;

#nullable disable

namespace PortfolioTrackerTool.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortfolioTrackerTool.Domain.Entities.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Investments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 3,
                            AssetType = "Crypto",
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bitcoin",
                            PricePerUnit = 32000m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10,
                            AssetType = "Crypto",
                            Date = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ethereum",
                            PricePerUnit = 2000m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 15,
                            AssetType = "Metal",
                            Date = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gold",
                            PricePerUnit = 3300m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 200,
                            AssetType = "Stock",
                            Date = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tesla",
                            PricePerUnit = 338m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 40,
                            AssetType = "Metal",
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Silver",
                            PricePerUnit = 1220m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 85,
                            AssetType = "Stock",
                            Date = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microsoft",
                            PricePerUnit = 513m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 440,
                            AssetType = "Stock",
                            Date = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IBM",
                            PricePerUnit = 240m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1,
                            AssetType = "Property",
                            Date = new DateTime(2025, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apartment",
                            PricePerUnit = 120000m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1,
                            AssetType = "Property",
                            Date = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "House",
                            PricePerUnit = 88000m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1,
                            AssetType = "Property",
                            Date = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Garage",
                            PricePerUnit = 12000m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 10,
                            AssetType = "Crypto",
                            Date = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BNB",
                            PricePerUnit = 830m,
                            TransactionType = "Buy"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 14,
                            AssetType = "Metal",
                            Date = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Platinum",
                            PricePerUnit = 1300m,
                            TransactionType = "Buy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
